# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MazeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Maze(object):
    def setupUi(self, Maze):
        Maze.setObjectName("Maze")
        Maze.resize(787, 619)
        self.tableWidget = QtWidgets.QTableWidget(Maze)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 541, 521))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame = QtWidgets.QFrame(Maze)
        self.frame.setGeometry(QtCore.QRect(620, 30, 111, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.easy = QtWidgets.QRadioButton(self.frame)
        self.easy.setGeometry(QtCore.QRect(20, 40, 61, 19))
        self.easy.setStyleSheet("font: 10pt \"黑体\";")
        self.easy.setChecked(True)
        self.easy.setObjectName("easy")
        self.medium = QtWidgets.QRadioButton(self.frame)
        self.medium.setGeometry(QtCore.QRect(20, 80, 61, 19))
        self.medium.setStyleSheet("font: 10pt \"黑体\";")
        self.medium.setObjectName("medium")
        self.hard = QtWidgets.QRadioButton(self.frame)
        self.hard.setGeometry(QtCore.QRect(20, 120, 61, 19))
        self.hard.setStyleSheet("font: 10pt \"黑体\";")
        self.hard.setObjectName("hard")
        self.mode = QtWidgets.QLabel(self.frame)
        self.mode.setGeometry(QtCore.QRect(20, 0, 71, 21))
        self.mode.setStyleSheet("font: 10pt \"黑体\";")
        self.mode.setObjectName("mode")
        self.spinBox = QtWidgets.QSpinBox(Maze)
        self.spinBox.setGeometry(QtCore.QRect(710, 220, 41, 31))
        self.spinBox.setMinimum(6)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.rank = QtWidgets.QLabel(Maze)
        self.rank.setGeometry(QtCore.QRect(610, 220, 91, 31))
        self.rank.setStyleSheet("font: 12pt \"黑体\";")
        self.rank.setObjectName("rank")
        self.trap = QtWidgets.QCheckBox(Maze)
        self.trap.setGeometry(QtCore.QRect(630, 300, 111, 20))
        self.trap.setStyleSheet("font: 12pt \"黑体\";")
        self.trap.setObjectName("trap")
        self.fire = QtWidgets.QCheckBox(Maze)
        self.fire.setGeometry(QtCore.QRect(630, 340, 111, 20))
        self.fire.setStyleSheet("font: 12pt \"黑体\";")
        self.fire.setObjectName("fire")
        self.getmaze = QtWidgets.QPushButton(Maze)
        self.getmaze.setGeometry(QtCore.QRect(630, 380, 93, 28))
        self.getmaze.setAutoFillBackground(False)
        self.getmaze.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"黑体\";")
        self.getmaze.setObjectName("getmaze")
        self.startlearn = QtWidgets.QPushButton(Maze)
        self.startlearn.setGeometry(QtCore.QRect(630, 520, 93, 28))
        self.startlearn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"黑体\";")
        self.startlearn.setObjectName("startlearn")
        self.label = QtWidgets.QLabel(Maze)
        self.label.setGeometry(QtCore.QRect(210, 10, 231, 31))
        self.label.setStyleSheet("font: 75 18pt \"Adobe Arabic\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.search = QtWidgets.QPushButton(Maze)
        self.search.setGeometry(QtCore.QRect(630, 570, 93, 28))
        self.search.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 9pt \"黑体\";")
        self.search.setObjectName("search")
        self.learn = QtWidgets.QLabel(Maze)
        self.learn.setGeometry(QtCore.QRect(610, 470, 91, 31))
        self.learn.setStyleSheet("font: 12pt \"黑体\";")
        self.learn.setObjectName("learn")
        self.epo = QtWidgets.QSpinBox(Maze)
        self.epo.setGeometry(QtCore.QRect(710, 470, 61, 31))
        self.epo.setMinimum(10)
        self.epo.setMaximum(10000)
        self.epo.setProperty("value", 100)
        self.epo.setObjectName("epo")
        self.eye = QtWidgets.QCheckBox(Maze)
        self.eye.setGeometry(QtCore.QRect(630, 430, 111, 20))
        self.eye.setStyleSheet("font: 12pt \"黑体\";")
        self.eye.setObjectName("eye")

        self.retranslateUi(Maze)
        QtCore.QMetaObject.connectSlotsByName(Maze)

    def retranslateUi(self, Maze):
        _translate = QtCore.QCoreApplication.translate
        Maze.setWindowTitle(_translate("Maze", "Form"))
        self.easy.setText(_translate("Maze", "简单"))
        self.medium.setText(_translate("Maze", "中等"))
        self.hard.setText(_translate("Maze", "困难"))
        self.mode.setText(_translate("Maze", "难度模式"))
        self.rank.setText(_translate("Maze", "迷宫阶数"))
        self.trap.setText(_translate("Maze", "加入鼠夹"))
        self.fire.setText(_translate("Maze", "加入火焰"))
        self.getmaze.setText(_translate("Maze", "生成迷宫"))
        self.startlearn.setText(_translate("Maze", "开始学习"))
        self.search.setText(_translate("Maze", "开始寻找"))
        self.learn.setText(_translate("Maze", "学习轮次"))
        self.eye.setText(_translate("Maze", "学习动画"))
